---
title: "cotton strips"
output: html_document
date: "2022-10-21"
---
```{r libraries}
library(tidyverse)
library(dplyr)
library(ggplot2)

```

```{r Data}
data <- read.csv("data/tensile_data_raw.csv")

merged <- data %>% 
  mutate(site.rep = paste0(Sample_ID, "_", Replicate.ID))

```

```{r plot}
ggplot(merged, aes(x = site.rep, y = Tensile.Strength, fill = Sample_ID))+
  geom_col()#+
  #theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

```

```{r Means}

#mean slope and standard deviation calculated for each site

means <- merged %>% 
  group_by(Sample_ID) %>% 
  mutate(mean(Tensile.Strength)) %>% 
  mutate(sd(Tensile.Strength))

means <- means %>%
  separate(Sample_ID, c("Sample", "type"), sep = "_", remove = FALSE) %>%
  rename("mean.ts" = "mean(Tensile.Strength)") %>% 
  rename("sd.ts" = "sd(Tensile.Strength)") %>% 
  distinct(mean.ts, .keep_all = TRUE) %>% 
  select(-Replicate.ID, -Tensile.Strength, -Notes.for.individual.reps, - Notes.for.group.of.4, - site.rep)

```

```{r Averages Plot}

ggplot(means, aes(x = Sample_ID, y = mean.ts)) +
  geom_col()+
  geom_errorbar(aes(ymin = mean.ts - sd.ts, ymax = mean.ts + sd.ts), width = 0.2)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggplot(means, aes(x = mean.ts))+
  geom_histogram()

```

```{r Respiration}
#does tensile strength correlate with lab respiration?

resp <- read.csv("data/SSS_ICON-ModEx_Sediment_Incubations_Respiration_Rates_merged_by_gara009_on_2022-08-19.csv")

#average respiration rate for now

mean.resp <- resp %>% 
  separate(Sample_ID, c("Sample", "rep"), sep = "-", remove = FALSE) %>%   group_by(Sample) %>% 
  mutate(mean(rate_mg_per_L_per_min)) %>% 
  mutate(sd(rate_mg_per_L_per_min)) %>% 
  mutate(mean(rate_mg_per_L_per_h)) %>% 
  mutate(sd(rate_mg_per_L_per_h)) %>% 
  rename("mean.rate.min" = "mean(rate_mg_per_L_per_min)") %>% 
  rename("sd.rate.min" = "sd(rate_mg_per_L_per_min)") %>% 
  rename("mean.rate.hr" = "mean(rate_mg_per_L_per_h)") %>% 
  rename("sd.rate.hr" = "sd(rate_mg_per_L_per_h)") %>% 
  distinct(mean.rate.min, .keep_all = TRUE) %>% 
  select(-slope_of_the_regression, - rate_mg_per_L_per_min, - rate_mg_per_L_per_h, -R_squared, - R_squared_adj, -p_value, -total_incubation_time_min, -number_of_points, -Sample_ID, -rep)

```

```{r lab resp v cotton strips}

ggplot()+
  geom_point(aes(x = means$mean.ts, y = mean.resp$mean.rate.hr, color = means$Sample))

```
```{r Dillman plots}
coeff <- 1

resp.ts <- full_join(means, mean.resp, by = 'Sample')

resp.ts.long <- resp.ts %>% 
  mutate(mean.rate.hr = mean.rate.hr*coeff) %>% 
  select(Sample, mean.ts, mean.rate.hr) %>% 
  pivot_longer(names_to = "y_new", values_to = "val", mean.rate.hr:mean.ts)

ggplot(resp.ts.long, aes(x = Sample))+
  geom_col(position = "dodge2", aes(y = val, fill = y_new))+
          scale_y_continuous(name = "Mean Tensile Strength", 
                             sec.axis = sec_axis(~.*coeff, name = "Mean Resp per Hour"))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))

ggplot(mean.resp, aes(x = Sample, y = mean.rate.hr))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

